apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: remove-stale-branches-location
  description: Links to additional entities in the remove-stale-branches repository.
  annotations:
    github.com/project-slug: Bandwidth/remove-stale-branches
spec:
  targets:
    - ./component.yaml
